# Generated by Django 2.0 on 2018-02-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180207_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Due',
            field=models.DateField(null=True),
        ),
    ]
